version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.30.1

    steps:
      - checkout

      - restore_cache:
          key: project-cache

      - run:
          name: Install Dependencies
          command: cargo install rustfmt
            
      - run:
          name: Check Formatting
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff

      - run:
          name: Build
          command: cargo build

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
