version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.30.1

    steps:
      - checkout

      - restore_cache:
          key: project-cache

      - run:
          name: Install rustfmt
          command:
            rustup component add rustfmt-preview

      - run:
          name: Check Formatting
          command: |
            cargo fmt -- --check

      - run:
          name: Build
          command: cargo build

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
